dataSource:
    driverClassName: com.mysql.cj.jdbc.Driver
    dbCreate: update
    username: root
    password: '1234'

environments:
    development:
        dataSource:
            dbCreate: update
            url: "jdbc:mysql://localhost/ordenaris?useUnicode=yes&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"
            username: root
            password: '1234'